spring:
  profiles:
    active: dev
---
server:
  port: 6001

spring:
  profiles: dev
  application:
    name: microservice-config-eureka
eureka:
  instance:
    hostname: eureka6001.com
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      default-zone: http://eureka6002.com:6002/eureka/
  server:
    enable-self-preservation: false
----

server:
  port: 6001
spring:
  profiles: prod
  application:
    name: microservice-config-eureka
eureka:
  instance:
    hostname: eureka6001.com
  client:
    registerWithEureka: false 
    fetchRegistry: false 
    serviceUrl:
      defaultZone: http://eureka6002.com:6002/eureka/
  server:
    enable-self-preservation: true


